name: Build and Deploy EDC to Cluster

on:
  push:
    branches: [ "develop", "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REGISTRY_NAMESPACE: possible-x
  K8S_NAMESPACE: ${{ github.ref == 'refs/heads/main' && 'mvd-001-demo' || 'edc-dev' }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Dev image tag
        if: startsWith(github.ref, 'refs/heads/')
        shell: bash {0}
        run: |
          tag="$(awk -F'"' '/"version": ".+"/{ print $4; exit; }' version)-$(git rev-parse --short HEAD)"
          echo "tag=$tag" >> $GITHUB_ENV
          echo "environment=dev" >> $GITHUB_ENV
      - name: Docker meta
        id: docker-meta-data
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/omejdn
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main'}}
            type=raw,value=${{env.tag}},enable=${{ github.ref == 'refs/heads/main'}}
            type=raw,value=latest-${{github.ref_name }},enable=${{ github.ref != 'refs/heads/main'}}
            ${{ github.sha }}
      - name: Build and push "management"
        id: build_and_push_management
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.docker-meta-data.outputs.tags }}
          labels: ${{ steps.management-meta.outputs.labels }}
          build-args: |
            ENVIRONMENT=${{ env.environment }}

